server:
  port: 8079

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: CLIENT-DEMO
          uri: lb://CLIENT-DEMO
          predicates:
            - Path=/client/**
            
        - id: DB-SERVICE
          uri: lb://DB-SERVICE
          predicates:
            - Path=/mvc/**
            - Path=/flux/**
            
        - id: USER-SERVICE
          uri: lb://USER-SERVICE 
          predicates:
            - Path=/users/**
            
        - id: REDIS-SERVICE
          uri: lb://REDIS-SERVICE 
          predicates:
            - Path=/logs/**
