server:
  port: 8086
  
spring:
  application:
    name: Redis-Service
    
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379  
    
  datasource:
    read:
      url: jdbc:mysql://localhost:3306/savvis2_read?useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    write:
      url: jdbc:mysql://localhost:3306/savvis2_write?useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    
logging:
  level:
    org:
      springframework:
        cloud:
          openfeign: DEBUG
    
    feign: DEBUG
    
    
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true 
    