server:
  port: 8085
  
spring:
  application:
    name: Client-Demo
    
logging:
  level:
    org:
      springframework:
        cloud:
          openfeign: DEBUG
    
    feign: DEBUG
    
    
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true 
    