server:
  port: 8081

spring:
  application:
    name: USER-MANAGEMENT	

  
  r2dbc:
    url: r2dbc:mysql://localhost:3306/user_db
    username: root
    password: root

logging:
  level:
    org.springframework.r2dbc: DEBUG